n1 = int(input("Diga um número: "))
n2 = int(input("Diga outro número: "))
Soma = n1 + n2
print(f'a soma é = {Soma}')
Multiplicacao = n1*n2
print(f'a multiplicação é = {Multiplicacao}')
subtracao = n1 - n2
print(f'a subtração é = {subtracao}')
divisao = n1 / n2
print(f'a divisão é = {divisao}')